# Generated by Django 2.2 on 2020-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
